install:
  - composer install

test:
  - vendor/bin/phpunit

# Files and directives specified under the "purge" directive will be deleted AFTER the install, build and test
# directives have run, but BEFORE the package is shipped to the server. The list is treated as a single array of
# globs and can therefore be used as a "whitelist" as well by exclusively specifying negating globs
purge:
  - "!web"
  - "!vendor"

# Files and directories specified under the "persistent" directive will persist through multiple deploys.
# This is achieved by creating a symbolic link to an equivalent location in ../shared.
# If the file exists in the package, but in the shared folder, it will first be copied.
persistent:
  - .env